name: bitproto ci

env:
  TZ: Asia/Shanghai

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-18.04]
        python: [3.7, 3.8, 3.9]
        go: [1.15, 1.14]

    runs-on: ${{ matrix.os  }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}

    - uses: actions/checkout@v2
    - name: Set up Golang ${{ matrix.go }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: Install requirements
      run: |
        pip install compiler/
        pip install -r compiler/requirements_dev.txt
        pip install lib/py/
        pip install -r lib/py/requirements_dev.txt

    - name: Run lints
      run: |
        make lint
      if: "matrix.python == '3.9'"

    - name: Run tests
      run: |
        make test
